name: Pytest & flake8 control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Install pytest & flake8
        run: |
          pip install pytest
          pip install flake8

      - name: Run tests
        run: |
          pytest

  create_commit:
    name: variables
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Push a file to our repo
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.AUTH_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          pip install pytest
          pytest >> log_pytest.txt
          ls -a -l
          git add .
          git commit -m "random file from action"
          git push
